from typing import Literal

CATEGORY_VALUES = [
    "FRAUD_UNAUTHORIZED_TX",
    "CHARGEBACK_DISPUTE",
    "TRANSFER_DELAY",
    "ACCESS_LOGIN_MOBILE",
    "CARD_LIMIT_CREDIT",
    "INFORMATION_REQUEST",
    "CAMPAIGN_POINTS_REWARDS",
]

CategoryLiteral = Literal[
    "FRAUD_UNAUTHORIZED_TX",
    "CHARGEBACK_DISPUTE",
    "TRANSFER_DELAY",
    "ACCESS_LOGIN_MOBILE",
    "CARD_LIMIT_CREDIT",
    "INFORMATION_REQUEST",
    "CAMPAIGN_POINTS_REWARDS",
]
